#!/usr/bin/env python3
"""Generate the embedded public WebUI assets from readable source files."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = PROJECT_ROOT / "webui"
OUTPUT_FILE = PROJECT_ROOT / "include" / "web" / "publicWebUi.h"


def _remove_css_comments(source: str) -> str:
    result = []
    index = 0
    quote = None

    while index < len(source):
        char = source[index]

        if quote is not None:
            result.append(char)
            if char == "\\" and index + 1 < len(source):
                index += 1
                result.append(source[index])
            elif char == quote:
                quote = None
            index += 1
            continue

        if char in ("'", '"'):
            quote = char
            result.append(char)
            index += 1
            continue

        if source.startswith("/*", index):
            comment_end = source.find("*/", index + 2)
            if comment_end == -1:
                raise ValueError("Unclosed CSS comment")
            index = comment_end + 2
            continue

        result.append(char)
        index += 1

    return "".join(result)


def _compact_css(source: str) -> str:
    source = _remove_css_comments(source)
    collapsed = []
    index = 0
    quote = None

    while index < len(source):
        char = source[index]

        if quote is not None:
            collapsed.append(char)
            if char == "\\" and index + 1 < len(source):
                index += 1
                collapsed.append(source[index])
            elif char == quote:
                quote = None
            index += 1
            continue

        if char in ("'", '"'):
            quote = char
            collapsed.append(char)
            index += 1
            continue

        if char.isspace():
            if collapsed and collapsed[-1] != " ":
                collapsed.append(" ")
            index += 1
            continue

        collapsed.append(char)
        index += 1

    compacted = []
    punctuation = set("{}:;,>+~")
    index = 0
    quote = None

    while index < len(collapsed):
        char = collapsed[index]

        if quote is not None:
            compacted.append(char)
            if char == "\\" and index + 1 < len(collapsed):
                index += 1
                compacted.append(collapsed[index])
            elif char == quote:
                quote = None
            index += 1
            continue

        if char in ("'", '"'):
            quote = char
            compacted.append(char)
            index += 1
            continue

        if char == " ":
            previous = compacted[-1] if compacted else ""
            following = collapsed[index + 1] if index + 1 < len(collapsed) else ""
            if previous in punctuation or following in punctuation:
                index += 1
                continue

        compacted.append(char)
        index += 1

    return "".join(compacted).strip()


def _compact_javascript(source: str) -> str:
    lines = []
    for line in source.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("//"):
            lines.append(stripped)
    return "\n".join(lines)


def _inject_build_values(source: str) -> str:
    language_placeholder = '"__PUBLIC_UI_LANGUAGE__"'
    io_placeholder = "__PUBLIC_UI_HAS_IO__"

    if source.count(language_placeholder) != 1:
        raise ValueError("Expected exactly one language placeholder")
    if source.count(io_placeholder) != 1:
        raise ValueError("Expected exactly one digital-I/O placeholder")

    source = source.replace(
        language_placeholder,
        "')rawliteral\" PUBLIC_UI_LANGUAGE R\"rawliteral('",
    )
    return source.replace(
        io_placeholder,
        ")rawliteral\" PUBLIC_UI_HAS_IO R\"rawliteral(",
    )


def build_public_webui() -> None:
    css_source = (SOURCE_DIR / "public-ui.css").read_text(encoding="utf-8")
    js_source = (SOURCE_DIR / "public-ui.js").read_text(encoding="utf-8")

    if ")rawliteral\"" in css_source or ")rawliteral\"" in js_source:
        raise ValueError("Source contains the C++ raw-string terminator")

    css = _compact_css(css_source)
    javascript = _inject_build_values(_compact_javascript(js_source))

    generated = f'''// AUTO-GENERATED FILE - DO NOT EDIT.
// Edit webui/public-ui.css and webui/public-ui.js instead.
// Generated by scripts/build_public_webui.py.

#ifndef PUBLIC_WEB_UI_H
#define PUBLIC_WEB_UI_H

#include <Arduino.h>

const char publicWebUiCss[] PROGMEM = R"rawliteral(
{css}
)rawliteral";

#ifdef TCONNECT
  #define PUBLIC_UI_HAS_IO "false"
#else
  #define PUBLIC_UI_HAS_IO "true"
#endif

#define PUBLIC_UI_STRINGIFY_INNER(value) #value
#define PUBLIC_UI_STRINGIFY(value) PUBLIC_UI_STRINGIFY_INNER(value)
#ifdef BUILD_LANG
  #define PUBLIC_UI_LANGUAGE PUBLIC_UI_STRINGIFY(BUILD_LANG)
#else
  #define PUBLIC_UI_LANGUAGE "de_DE"
#endif

const char publicWebUiJs[] PROGMEM = R"rawliteral(
{javascript}
)rawliteral";

#undef PUBLIC_UI_LANGUAGE
#undef PUBLIC_UI_STRINGIFY
#undef PUBLIC_UI_STRINGIFY_INNER
#undef PUBLIC_UI_HAS_IO

#endif
'''

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    if not OUTPUT_FILE.exists() or OUTPUT_FILE.read_text(encoding="utf-8") != generated:
        OUTPUT_FILE.write_text(generated, encoding="utf-8")
        print(f"Generated {OUTPUT_FILE.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    build_public_webui()
