/* Copyright (c) 2022 tobias
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

#include "Arduino.h"
#include "defines.h"
#include "WebSettings.h"

/* ***********************************************************************************
 * Wichtiger Hinweis!
 * params.h nicht manuell bearbeiten! Änderungen immer in der params_py.h vornehmen!
 * Die params.h wird beim Build automatisch erstellt!
 * ***********************************************************************************/


//PY_VAR_ANF
const String comboAlarms PROGMEM = ""
  "{'v':'1','l':'Trigger 1','d':7488},"
  "{'v':'2','l':'Trigger 2','d':7489},"
  "{'v':'3','l':'Trigger 3','d':7490},"
  "{'v':'4','l':'Trigger 4','d':7491},"
  "{'v':'5','l':'Trigger 5','d':7492},"
  "{'v':'6','l':'Trigger 6','d':7493},"
  "{'v':'7','l':'Trigger 7','d':7494},"
  "{'v':'8','l':'Trigger 8','d':7495},"
  "{'v':'9','l':'Trigger 9','d':7496},"
  "{'v':'10','l':'Trigger 10','d':7497}";
//PY_VAR_END

//PY_VAR_ANF
const String bmsDeviceAll PROGMEM = ""
  "{'v':'0','l':'Bluetooth 0'},"
  "{'v':'1','l':'Bluetooth 1'},"
  "{'v':'2','l':'Bluetooth 2'},"
  "{'v':'3','l':'Bluetooth 3'},"
  "{'v':'4','l':'Bluetooth 4'},"
  "{'v':'5','l':'Bluetooth 5'},"
  "{'v':'6','l':'Bluetooth 6'},"
  "{'v':'7','l':'Serial 0'},"
  "{'v':'8','l':'Serial 1'},"
  "{'v':'9','l':'Serial 2'},"
  "{'v':'10','l':'Serial 3'},"
  "{'v':'11','l':'Serial 4'},"
  "{'v':'12','l':'Serial 5'},"
  "{'v':'13','l':'Serial 6'},"
  "{'v':'14','l':'Serial 7'},"
  "{'v':'15','l':'Serial 8'},"
  "{'v':'16','l':'Serial 9'},"
  "{'v':'17','l':'Serial 10'}";
//PY_VAR_END

//PY_VAR_ANF
const String dataDevicesAll PROGMEM = ""
  "{'v':'0','l':'Data device 0','d':10560},"
  "{'v':'1','l':'Data device 1','d':10561},"
  "{'v':'2','l':'Data device 2','d':10562},"
  "{'v':'3','l':'Data device 3','d':10563},"
  "{'v':'4','l':'Data device 4','d':10564},"
  "{'v':'5','l':'Data device 5','d':10565},"
  "{'v':'6','l':'Data device 6','d':10566},"
  "{'v':'7','l':'Data device 7','d':10567},"
  "{'v':'8','l':'Data device 8','d':10568},"
  "{'v':'9','l':'Data device 9','d':10569},"
  "{'v':'10','l':'Data device 10','d':10570},"
  "{'v':'11','l':'Data device 11','d':10571},"
  "{'v':'12','l':'Data device 12','d':10572},"
  "{'v':'13','l':'Data device 13','d':10573},"
  "{'v':'14','l':'Data device 14','d':10574},"
  "{'v':'15','l':'Data device 15','d':10575},"
  "{'v':'16','l':'Data device 16','d':10576},"
  "{'v':'17','l':'Data device 17','d':10576}";
//PY_VAR_END


const String paramSystem PROGMEM = "{'page':["
  //"{"
  //  "'label':'Master/Slave',"
  //  "'type':"+String(HTML_SEPARATION)+","
  //"},"
  //"{"
  //  "'name':"+String(ID_PARAM_MASTER_SLAVE_TYP)+","
  //  "'label':'Master/Slave',"
  //  "'type':"+String(HTML_INPUTSELECT)+","
  //  "'options':["
  //    "{'v':'"+String(ID_I2C_MASTER)+"','l':'Master'},"
  //    "{'v':'"+String(I2C_DEV_ADDR_SLAVE1)+"','l':'Slave 0'},"
  //    "{'v':'"+String(I2C_DEV_ADDR_SLAVE2)+"','l':'Slave 1'}"
  //  "],"
  //  "'default':'0'"
  //"},"

  //"{"
  //  "'name':"+String(ID_PARAM_I_AM_A_SUPPORTER)+","
  //  "'label':'WebUI v2 aktivieren',"
  //  "'type':"+String(HTML_INPUTCHECKBOX)+","
  //  "'default':0,"
  //  "'dt':"+String(PARAM_DT_BO)+","
  //  "'flash':'1',"
  //  "'help':'Willst du das Projekt unterst&uuml;tzen? Weitere Infos gibt es <a href=\"../../support/\">hier<a/>.'"
  //"},"

  "{"
    "'name':"+String(ID_PARAM_BSC_USERNAME)+","
    "'label':'BSC Benutzer',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'bsc',"
    "'dt':"+String(PARAM_DT_ST)+","
    "'flash':'1'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_BSC_PASSWORD)+","
    "'label':'BSC Passwort',"
    "'type':"+String(HTML_INPUTPASSWORD)+","
    "'default':'admin',"
    "'dt':"+String(PARAM_DT_ST)+","
    "'flash':'1'"
  "},"

  "{"
    "'name':"+String(ID_PARAM_MQTT_DEVICE_NAME)+","
    "'label':'Device Name',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'bsc',"
    "'minlen':3,"
    "'dt':"+String(PARAM_DT_ST)+","
    "'help':'Wird auch als MQTT device name genutzt'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_DISPLAY_TIMEOUT)+","
    "'label':'Display timeout',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':5,"
    "'min':1,"
    "'max':120,"
    "'unit':'min',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'WLAN',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_SSID)+","
    "'label':'WLAN SSID',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_PWD)+","
    "'label':'WLAN Passwort',"
    "'type':"+String(HTML_INPUTPASSWORD)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_CONNECT_TIMEOUT)+","
    "'label':'WLAN connect Timeout',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'unit':'s',"
    "'default':30,"
    "'min':0,"
    "'max':3600,"
    "'dt':"+String(PARAM_DT_U16)+","
    "'help':'Der Timeout gibt an, nach welcher Zeit ein Verbindungsversuch abgebrochen wird und ein Accesspoint erstellt wird.\n0 deaktiviert den Timeout.'"
  "},"

  "{"
    "'label':'Static IP',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_IP_ADRESSE)+","
    "'label':'IP-Adresse',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+","
    "'flash':'1',"
    "'help':'Wenn die IP-Adresse leer ist, dann ist DHCP aktiv'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_GATEWAY)+","
    "'label':'Gateway',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+","
    "'flash':'1'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_SUBNET)+","
    "'label':'Subnet',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'255.255.255.0',"
    "'dt':"+String(PARAM_DT_ST)+","
    "'flash':'1'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_WLAN_DNS)+","
    "'label':'DNS',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+","
    "'help':'Optional',"
    "'flash':'1'"
  "},"

  "{"
    "'label':'MQTT',"
    "'type':"+String(HTML_SEPARATION)+","
    "'help':'Zum Übernehmen der Settings, muss der BSC neu gestartet werden!'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_SERVER_ENABLE)+","
    "'label':'MQTT enable',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':0,"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_SERVER_IP)+","
    "'label':'MQTT Server IP',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_SERVER_PORT)+","
    "'label':'MQTT Server Port',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':1883,"
    "'min':1,"
    "'max':49151,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_USERNAME)+","
    "'label':'Username',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_PWD)+","
    "'label':'Passwort',"
    "'type':"+String(HTML_INPUTPASSWORD)+","
    "'default':'',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_TOPIC_NAME)+","
    "'label':'MQTT Topic Name',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'bsc',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_MQTT_SEND_DELAY)+","
    "'label':'MQTT Sendeintervall',"
    "'unit':'s',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':60,"
    "'min':30,"
    "'max':120,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'NTP',"
    "'type':"+String(HTML_SEPARATION)+","
    "'help':'Zum Übernehmen der Settings, muss der BSC neu gestartet werden!'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_SYSTEM_NTP_SERVER_NAME)+","
    "'label':'Server Name/IP',"
    "'type':"+String(HTML_INPUTTEXT)+","
    "'default':'pool.ntp.org',"
    "'flash':'1',"
    "'dt':"+String(PARAM_DT_ST)+""
  "},"
  //"{"
  //  "'name':"+String(ID_PARAM_SYSTEM_NTP_SERVER_PORT)+","
  //  "'label':'Server Port',"
  //  "'type':"+String(HTML_INPUTNUMBER)+","
  //  "'default':1337,"
  //  "'min':1,"
  //  "'max':32000,"
  //  "'flash':'1',"
  //  "'dt':"+String(PARAM_DT_U16)+""
  //"},"

  "{"
    "'label':'Aufzeichnung',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_SYSTEM_RECORD_VALUES_PERIODE)+","
    "'label':'Aufzeichnung Periode',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':0,'l':'Aus'},"
      "{'v':1,'l':'24h'}"
      "],"
    "'default':0,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'Triggername',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'label':'Trigger description',"
    "'label_entry':'Trigger',"
    "'label_offset':1,"
    "'groupsize':"+String(CNT_ALARMS)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
    "{"
      "'name':"+String(ID_PARAM_TRIGGER_NAMES)+","
      "'label':'Trigger',"
      "'type':"+String(HTML_INPUTTEXT)+","
      "'default':'',"
      "'flash':'1',"
      "'dt':"+String(PARAM_DT_ST)+""
    "}]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


const String paramBluetooth PROGMEM = "{'page':["
  "{"
    "'label':'Bluetooth',"
    "'label_entry':'BT Device',"
    "'groupsize':"+String(BT_EXT_DEVICES_COUNT)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'help':'Die MAC-Adresse muss klein geschrieben werden!',"
    "'group':["
    "{"
      "'name':"+String(ID_PARAM_SS_BTDEV)+","
      "'label':'Bluetooth',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'"+String(ID_BT_DEVICE_NB)+"','l':'nicht belegt'},"
        "{'v':'"+String(ID_BT_DEVICE_NEEY4A)+"','l':'NEEY Balancer 4A (GW-24S4EB)'},"
        "{'v':'"+String(ID_BT_DEVICE_NEEY8A)+"','l':'EK-24S4EB'},"
        "{'v':'"+String(ID_BT_DEVICE_JKBMS_JK02)+"','l':'JK-BMS [Test]'},"
        "{'v':'"+String(ID_BT_DEVICE_JKBMS_JK02_32S)+"','l':'JK-BMS (32S) [Test]'}],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
    "},"
    "{"
      "'name':"+String(ID_PARAM_SS_BTDEVMAC)+","
      "'label':'MAC-Adresse',"
      "'type':"+String(HTML_INPUTTEXT)+","
      "'default':'',"
      "'dt':"+String(PARAM_DT_ST)+""
    "},"
    "{"
      "'name':"+String(ID_PARAM_BTDEV_DEACTIVATE)+","
      "'label':'Deactivate',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Aus'},"
        +comboAlarms+
        "],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
    "}]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}],"
  "'timer':[{'type':'text','interval':2000}]"
  "}";


const String paramSerial PROGMEM = "{'page':["
  "{"
    "'label':'Serielle Schnittstellen',"
    "'label_entry':'Serial',"
    "'help':'<b>To use serial 3-11, the serial extension is required!</b>',"
    "'groupsize':11,"
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
        "'name':"+String(ID_PARAM_SERIAL_CONNECT_DEVICE)+","
        "'label':'Serial',"
        "'type':"+String(HTML_INPUTSELECT)+","
        "'options':["
          "{'v':'"+String(ID_SERIAL_DEVICE_NB)+"','l':'nicht belegt'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_BPN)+"','l':'BPN (not use)'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_JBDBMS)+"','l':'JBD BMS'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_JKBMS)+"','l':'JK BMS'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_JKBMS_V13)+"','l':'JK BMS V1.3 (only monitoring)'},"
//          "{'v':'"+String(ID_SERIAL_DEVICE_JKBMS_CAN)+"','l':'JK BMS - CAN (Test; only monitoring)'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_JKINVERTERBMS)+"','l':'JK Inverter BMS'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_SEPLOSBMS)+"','l':'Seplos BMS'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_SEPLOSBMS_V3)+"','l':'Seplos V3 BMS (Test)'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_DALYBMS)+"','l':'DALY BMS'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_SYLCINBMS)+"','l':'Sylcin BMS'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_GOBELBMS)+"','l':'Gobel RN150 BMS (Test)'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_GOBEL_PC200)+"','l':'Gobel PC200 BMS (Test)'},"
//          "{'v':'"+String(ID_SERIAL_DEVICE_NEEY_4A)+"','l':'NEEY 4A Balancer (Test)'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_PYLONTECH)+"','l':'Pylontech'},"
          "{'v':'"+String(ID_SERIAL_DEVICE_SMARTSHUNT_VEDIRECT)+"','l':'Victron SmartShunt'}"
          "],"
        "'default':'"+String(ID_SERIAL_DEVICE_NB)+"',"
        "'dt':"+String(PARAM_DT_U8)+""
      "}"
    "]"
  "},"


  //
  "{"
    "'label':'Allgemein',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_SERIAL_NUMBER_OF_CELLS)+","
    "'label':'Anzahl Zellen',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':16,"
    "'min':4,"
    "'max':24,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  //Filter
  "{"
    "'label':'Filter',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_FILTER_RX_ERROR_COUNT)+","
    "'label':'Anzahl RX Fehler',"
    "'help':'Gibt an, nach wievielen fehlerhaften Paketen es als Fehler bewertet wird.',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':2,"
    "'min':1,"
    "'max':125,"
    "'flash':'1',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_FILTER_CELL_VOLTAGE_PERCENT)+","
    "'label':'Abweichung Zellspannung',"
    "'help':'0=Filter deaktiviert',"
    "'unit':'%',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':0,"
    "'min':0,"
    "'max':100,"
    "'flash':'1',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  //Cell voltage plausibility check
  "{"
    "'label':'Plausibility check',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_PLAUSIBILITY_CHECK_CELLVOLTAGE)+","
    "'label':'Cellvoltage plausibility check',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Aus'},"
      +comboAlarms+
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  //Value adjustments
  "{"
    "'label':'Value adjustments',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'label':'Data devices',"
    "'label_entry':'Device',"
    "'groupsize':"+String(MUBER_OF_DATA_DEVICES)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
        "'name':"+String(ID_PARAM_BMS_BALUE_ADJUSTMENTS_SOC100_CELL_VOLTAGE)+","
        "'label':'Cellvoltage for SoC 100%',"
        "'help':'0=deaktiviert',"
        "'unit':'mV',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':0,"
        "'min':0,"
        "'max':5000,"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_BMS_BALUE_ADJUSTMENTS_SOC0_CELL_VOLTAGE)+","
        "'label':'Cellvoltage for SoC 0%',"
        "'help':'0=deaktiviert',"
        "'unit':'mV',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':0,"
        "'min':0,"
        "'max':5000,"
        "'dt':"+String(PARAM_DT_U16)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";

const String paramAlarmBms PROGMEM = "{'page':["
  "{"
    "'label':'BMS Alarmregeln',"
    "'label_entry':'Alarmregel',"
    "'groupsize':"+String(CNT_BT_ALARMS_RULES)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
      "'name':"+String(ID_PARAM_ALARM_BTDEV_BMS_SELECT)+","
      "'label':'Zu &uuml;berwachendes BMS',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'255','l':'Aus'},"
        +dataDevicesAll+
        "],"
      "'default':255,"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'label':'Keine Daten vom BMS',"
        "'type':"+String(HTML_SEPARATION)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_ALARM_BTDEV_ALARM_AKTION)+","
      "'label':'Aktion bei Trigger',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Aus'},"
        +comboAlarms+
        "],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BTDEV_ALARM_TIME_OUT)+","
        "'label':'Trigger keine Daten',"
        "'unit':'s',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':15,"
        "'min':1,"
        "'max':255,"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'label':'Spannungs&uuml;berwachung Zelle Min/Max',"
        "'type':"+String(HTML_SEPARATION)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_ALARM_BT_CELL_SPG_ALARM_AKTION)+","
      "'label':'Aktion bei Trigger',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Aus'},"
        +comboAlarms+
        "],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BT_CNT_CELL_CTRL)+","
        "'label':'Anzahl Zellen Monitoring',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':16,"
        "'min':1,"
        "'max':24,"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BT_CELL_SPG_MIN)+","
        "'label':'Zellspannung Min',"
        "'unit':'mV',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':2500,"
        "'min':0,"
        "'max':5000,"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BT_CELL_SPG_MAX)+","
        "'label':'Zellspannung Max',"
        "'unit':'mV',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':3650,"
        "'min':0,"
        "'max':5000,"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      //"{"
      //  "'name':"+String(ID_PARAM_ALARM_BT_CELL_SPG_MAX_HYSTERESE)+","
      //  "'label':'Hysterese',"
      //  "'unit':'mV',"
      //  "'type':"+String(HTML_INPUTNUMBER)+","
      //  "'default':20,"
      //  "'min':0,"
      //  "'max':255,"
      //  "'dt':"+String(PARAM_DT_U8)+""
      //"},"
      "{"
        "'label':'Spannungs&uuml;berwachung Gesamt Min/Max',"
        "'type':"+String(HTML_SEPARATION)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_ALARM_BT_GESAMT_SPG_ALARM_AKTION)+","
      "'label':'Aktion bei Trigger',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Aus'},"
        +comboAlarms+
        "],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BT_GESAMT_SPG_MIN)+","
        "'label':'Spannung Min',"
        "'unit':'V',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':48.0,"
        "'min':0,"
        "'max':66,"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BT_GESAMT_SPG_MAX)+","
        "'label':'Spannung Max',"
        "'unit':'V',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':54.0,"
        "'min':0,"
        "'max':66,"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_ALARM_BT_GESAMT_SPG_HYSTERESE)+","
        "'label':'Hysterese Min/Max',"
        "'unit':'V',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':0.5,"
        "'min':0,"
        "'max':10,"
        "'dt':"+String(PARAM_DT_FL)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


const String paramAlarmTemp PROGMEM = "{'page':["
  //Alarm bei Sensorfehler
  "{"
    "'label':'Alarm bei Sensorfehler',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_TEMP_SENSOR_TIMEOUT_TRIGGER)+","
    "'label':'Trigger',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
    "{'v':'0','l':'Aus'},"
    +comboAlarms+
    "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_TEMP_SENSOR_TIMEOUT_TIME)+","
    "'label':'Timeout',"
    "'unit':'s',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'5',"
    "'min':5,"
    "'max':240,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'Temperatur &#220;berwachung',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_TEMP_ALARM)+","
    "'label':'Temperatur &#220;berwachung',"
    "'label_entry':'&#220;berwachung',"
    "'groupsize':"+String(COUNT_TEMP_RULES)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_TEMP_QUELLE)+","
        "'label':'Quelle',"
        "'type':"+String(HTML_INPUTSELECT)+","
        "'options':["
          "{'v':'1','l':'BMS'},"
          "{'v':'2','l':'Onewire'}"
          "],"
        "'default':'1',"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_TEMP_ALARM_BMS_QUELLE)+","
      "'label':'Zu &uuml;berwachendes BMS (nur wenn Quelle BMS)',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        +dataDevicesAll+
        "],"
      "'default':7,"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_SENSOR_VON)+","
        "'label':'Sensornummer von',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':'',"
        "'min':0,"
        "'max':255,"
        "'dt':"+String(PARAM_DT_U8)+","
        "'help':'Mögliche Werte:\nBMS:0-2\nOnewire:0-63'"
      "},"
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_SENSOR_BIS)+","
        "'label':'Sensornummer bis',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':'',"
        "'min':0,"
        "'max':255,"
        "'dt':"+String(PARAM_DT_U8)+","
        "'help':'Mögliche Werte:\nBMS:0-2\nOnewire:0-63'"
      "},"
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_UEBERWACH_FUNKTION)+","
        "'label':'&Uuml;berwachung',"
        "'type':"+String(HTML_INPUTSELECT)+","
        "'options':["
          "{'v':'"+String(ID_TEMP_ALARM_FUNKTION_NB)+"','l':'nicht belegt'},"
          "{'v':'"+String(ID_TEMP_ALARM_FUNKTION_MAXWERT)+"','l':'Maximalwert-&Uuml;berschreitung'},"
          "{'v':'"+String(ID_TEMP_ALARM_FUNKTION_MAXWERT_REFERENZ)+"','l':'Maximalwert-&Uuml;berschreitung (Referenz)'},"
          "{'v':'"+String(ID_TEMP_ALARM_FUNKTION_DIFFERENZ)+"','l':'Differenzwert-&Uuml;berwachung'}],"
        "'default':'"+String(ID_TEMP_ALARM_FUNKTION_NB)+"',"
        "'dt':"+String(PARAM_DT_U8)+","
        "'help':'Maximalwert-&Uuml;berschreitung: Wert1=Maximale Temperatur\nMaximalwert-&Uuml;berschreitung (Referenz): Wert1=Temperatur Offset\nDifferenzwert-&Uuml;berwachung: Wert1=Maximal erlaubte Differenz'"
      "},"
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_SENSOR_VERGLEICH)+","
        "'label':'Referenzsensor',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':'',"
        "'min':0,"
        "'max':255,"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_WERT1)+","
        "'label':'Wert 1',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':'',"
        "'min':0,"
        "'max':70,"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_TEMP_ALARM_WERT2)+","
        "'label':'Hysterese',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':'',"
        "'min':0,"
        "'max':70,"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_TEMP_ALARM_AKTION)+","
      "'label':'Ausl&ouml;sung',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Aus'},"
        +comboAlarms+
        "],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


//Relaisausgang 1..6
const String paramDigitalOut PROGMEM = "{'page':["
  "{"
    "'label':'Relaisausg&#228;nge',"
    "'label_entry':'Relaisausgang',"
    "'groupsize':6,"
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
      "'name':"+String(ID_PARAM_DO_AUSLOESEVERHALTEN)+","
      "'label':'Ausl&#246;severhalten',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Permanent'},"
        "{'v':'1','l':'Impuls'}],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_DO_IMPULSDAUER)+","
        "'label':'Impulsdauer',"
        "'unit':'ms',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':500,"
        "'min':100,"
        "'max':10000,"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_DO_VERZOEGERUNG)+","
        "'label':'Verz&ouml;gerung',"
        "'unit':'s',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':0,"
        "'min':0,"
        "'max':254,"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_REL_INVERTIERT)+","
        "'label':'Invertieren',"
        "'type':"+String(HTML_INPUTCHECKBOX)+","
        "'default':'0',"
        "'dt':"+String(PARAM_DT_BO)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_DO_AUSLOESUNG_BEI)+","
      "'label':'Auswahl Trigger',"
      "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
      "'options':["
        +comboAlarms+
        "],"
      "'default':'',"
      "'dt':"+String(PARAM_DT_U16)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


//Digitaleingänge 1..4
const String paramDigitalIn PROGMEM = "{'page':["
  "{"
    "'label':'Digitaleing&#228;nge',"
    "'label_entry':'Digitaleingang',"
    "'groupsize':4,"
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
      "'name':"+String(ID_PARAM_DI_INVERTIERT)+","
      "'label':'Eingang invertieren',"
      "'type':"+String(HTML_INPUTCHECKBOX)+","
      "'default':'0',"
      "'dt':"+String(PARAM_DT_BO)+""
      "},"
      "{"
      "'name':"+String(ID_PARAM_DI_ALARM_NR)+","
      "'label':'Weiterleiten an',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'0','l':'Aus'},"
        +comboAlarms+
        "],"
      "'default':'0',"
      "'dt':"+String(PARAM_DT_U8)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


const String paramOnewireAdr PROGMEM = "{'page':["
  "{"
  "'name':"+String(ID_PARAM_ONWIRE_ENABLE)+","
  "'label':'Onewire enable',"
  "'type':"+String(HTML_INPUTCHECKBOX)+","
  "'default':'0',"
  "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'label':'OW Adressen',"
    "'label_entry':'OW Adr.',"
    "'groupsize':"+String(MAX_ANZAHL_OW_SENSOREN)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':[{"
      "'name':"+String(ID_PARAM_ONEWIRE_ADR)+","
      "'label':'OW Adr.',"
      "'type':"+String(HTML_INPUTTEXT)+","
      "'default':'',"
      "'flash':'1',"
      "'dt':"+String(PARAM_DT_ST)+""
    "}]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}],"
  "'timer':[{'type':'text','interval':2000}]"
  "}";


const String paramOnewire2 PROGMEM = "{'page':["
  "{"
    "'label':'Onewire Sensoren',"
    "'label_entry':'Sensor',"
    "'groupsize':"+String(MAX_ANZAHL_OW_SENSOREN)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
        "'name':"+String(ID_PARAM_ONWIRE_TEMP_OFFSET)+","
        "'label':'Offset',"
        "'unit':'&deg;C',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':0,"
        "'min':-10,"
        "'max':10,"
        "'dt':"+String(PARAM_DT_FL)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";




//BMS to Inverter
const String paramBmsToInverter PROGMEM = "{'page':["
  "{"
    "'name':"+String(ID_PARAM_BMS_CAN_ENABLE)+","
    "'label':'BMS Canbus enable',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_SS_CAN)+","
    "'label':'Canbus protocol',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'"+String(ID_CAN_DEVICE_NB)+"','l':'nicht belegt'},"
      "{'v':'"+String(ID_CAN_DEVICE_SOLISRHI)+"','l':'Solis RHI'},"
      "{'v':'"+String(ID_CAN_DEVICE_PYLONTECH)+"','l':'Pylontech'},"
      "{'v':'"+String(ID_CAN_DEVICE_VICTRON)+"','l':'VICTRON'},"
      "{'v':'"+String(ID_CAN_DEVICE_VICTRON_250K)+"','l':'VICTRON 250k'},"
      "{'v':'"+String(ID_CAN_DEVICE_BYD_PROTOCOL)+"','l':'BYD'}],"
    "'default':'nb',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_CAN_EXTENDED_DATA_ENABLE)+","
    "'label':'Send extended data',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+","
    "'help':'Nicht in Verbindung mit einem CerboGX aktivieren!'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_CAN_DATASOURCE)+","
    "'label':'Datenquelle (Master)',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      +dataDevicesAll+
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'name':"+String(ID_PARAM_BMS_CAN_DATASOURCE_SS1)+","
    "'label':'\+ Datenquelle',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +dataDevicesAll+
    "],"
    "'default':0,"
    "'dt':"+String(PARAM_DT_U32)+""
  "},"

  //Multi-BMS Settings
  "{"
    "'label':'Valuehandling Multi-BMS',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_MULTI_BMS_VALUE_SOC)+","
    "'label':'SoC',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Masterquelle'},"
      "{'v':"+String(OPTION_MULTI_BMS_SOC_AVG)+",'l':'SoC Mittelwert'},"
      "{'v':"+String(OPTION_MULTI_BMS_SOC_MAX)+",'l':'SoC Maximalwert'},"
      "{'v':"+String(OPTION_MULTI_BMS_SOC_BMS)+",'l':'BMS'}],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_BMS_QUELLE_SOC)+","
    "'label':'BMS für SoC',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      +dataDevicesAll+
      "],"
    "'default':7,"
    "'dt':"+String(PARAM_DT_U8)+","
//    "'dependence':{'depId':"+String(ID_PARAM_INVERTER_MULTI_BMS_VALUE_SOC)+",'depDt':1,'depGte':[3],'getSte':[3]},"
    "'help':'Hierfür muss bei SoC BMS ausgewählt sein'"
  "},"

  "{"
    "'label':'Basisdaten',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_MAX_CHARGE_SPG)+","
    "'label':'Absorption Ladespannung',"
    "'unit':'V',"
    "'type':"+String(HTML_INPUTFLOAT_1)+","
    "'default':'544',"
    "'min':12,"
    "'max':66,"
    "'dt':"+String(PARAM_DT_U16)+","
    "'help':'Die Absorption Ladespannung entspricht einer erhöhten Spannung zum Erreichen des Voll-Zustandes.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_FLOAT_CHARGE_SPG)+","
    "'label':'Float Ladespannung',"
    "'unit':'V',"
    "'type':"+String(HTML_INPUTFLOAT_1)+","
    "'default':'544',"
    "'min':12,"
    "'max':66,"
    "'dt':"+String(PARAM_DT_U16)+","
    "'help':'Die Floatspannung wird nach Erreichen der einstellbaren Cutoff-Funktion angewendet.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_CURRENT_CUT_OFF_SOC)+","
    "'label':'Float Ladespannung SoC',"
    "'unit':'%',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'95',"
    "'min':1,"
    "'max':100,"
    "'dt':"+String(PARAM_DT_U8)+","
    "'help':'Beim Unterschreiten des eingestellten SoC wird von der Float in die Absorption Ladespannung gewechselt.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_MAX_CHARGE_CURRENT)+","
    "'label':'Max. Ladestrom',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'100',"
    "'min':0,"
    "'max':1000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_MAX_DISCHARGE_CURRENT)+","
    "'label':'Max. Entladestrom',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'100',"
    "'min':0,"
    "'max':1000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_LADELEISTUNG_AUF_NULL)+","
    "'label':'Ladeleistung auf 0 bei',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_ENTLADELEISTUNG_AUF_NULL)+","
    "'label':'Entladeleistung auf 0 bei',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_SOC_AUF_FULL)+","
    "'label':'SOC auf 100 bei',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'label':'Batterypack settings',"
    "'label_entry':'BMS Serial',"
    "'groupsize':11,"
    "'type':"+String(HTML_OPTIONGROUP_COLLAPSIBLE)+","
    "'group':["
      "{"
        "'name':"+String(ID_PARAM_BATTERY_PACK_CHARGE_CURRENT)+","
        "'label':'Charge current per pack',"
        "'unit':'A',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':280,"
        "'min':0,"
        "'max':500,"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_BATTERY_PACK_DISCHARGE_CURRENT)+","
        "'label':'Discharge current per pack',"
        "'unit':'A',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':280,"
        "'min':0,"
        "'max':500,"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_BATTERY_PACK_CAPACITY)+","
        "'label':'Kapazität',"
        "'unit':'Ah',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':280,"
        "'min':1,"
        "'max':1000,"
        "'dt':"+String(PARAM_DT_U16)+""
      "}]"
  "},"

  // Dynamic charge voltage offset
  //"{"
  //  "'label':'Dynamic charge voltage offset',"
  //  "'type':"+String(HTML_SEPARATION)+","
  //  "'help':'Mit der Funktion kann die Ladespannung dynamisch nach dem Ladestrom angepasst werden.\nDer Offset ist linear abhängig vom Ladestrom. Als Strom für die Berechnung wird der kleinste Ladestrom der Batterypacks genommen.'"
  //"},"
  //"{"
  //  "'name':"+String(ID_PARAM_DYNAMIC_CHARGE_VOLTAGE_CURRENT)+","
  //  "'label':'Strom',"
  //  "'unit':'A',"
  //  "'type':"+String(HTML_INPUTNUMBER)+","
  //  "'default':'0',"
  //  "'min':0,"
  //  "'max':1000,"
  //  "'dt':"+String(PARAM_DT_U16)+","
  //  "'help':'0=deaktiviert\nDer Strom, bei dem der maximale Offset addiert wird.'"
  //"},"
  //"{"
  //  "'name':"+String(ID_PARAM_DYNAMIC_CHARGE_VOLTAGE_OFFSET_MIN)+","
  //  "'label':'Min. Offset',"
  //  "'unit':'mV',"
  //  "'type':"+String(HTML_INPUTNUMBER)+","
  //  "'default':'0',"
  //  "'min':0,"
  //  "'max':5000,"
  //  "'dt':"+String(PARAM_DT_U16)+""
  //"},"
  //"{"
  //  "'name':"+String(ID_PARAM_DYNAMIC_CHARGE_VOLTAGE_OFFSET_MAX)+","
  //  "'label':'Max. Offset',"
  //  "'unit':'mV',"
  //  "'type':"+String(HTML_INPUTNUMBER)+","
  //  "'default':'500',"
  //  "'min':0,"
  //  "'max':5000,"
  //  "'dt':"+String(PARAM_DT_U16)+""
  //"},"

  //Alarm über Trigger
  "{"
    "'label':'Alarme (Inverter)',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_ALARM_HIGH_BAT_VOLTAGE)+","
    "'label':'High battery voltage',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U32)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_ALARM_LOW_BAT_VOLTAGE)+","
    "'label':'Low battery voltage',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U32)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_ALARM_HIGH_TEMPERATURE)+","
    "'label':'High Temperature',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U32)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_BMS_ALARM_LOWTEMPERATURE)+","
    "'label':'Low Temperature',"
    "'type':"+String(HTML_INPUTMULTICHECK_COLLAPSIBLE)+","
    "'options':["
      +comboAlarms+
      "],"
    "'default':'',"
    "'dt':"+String(PARAM_DT_U32)+""
  "},"

  "{"
    "'label':'Batterietemperatur',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_BATT_TEMP_QUELLE)+","
    "'label':'Quelle',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'1','l':'BMS'},"
      "{'v':'2','l':'Onewire'}"
      "],"
    "'default':'1',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_BATT_TEMP_SENSOR)+","
    "'label':'Sensornummer',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'0',"
    "'min':0,"
    "'max':64,"
    "'dt':"+String(PARAM_DT_U8)+","
    "'help':'Mögliche Werte:\nBMS:0-2\nOnewire:0-63'"
  "},"

  //Trigger bei SoC
  "{"
    "'label':'Trigger bei SoC',"
    "'type':"+String(HTML_SEPARATION)+","
    "'help':'Auslösen eines Triggers, wenn ein bestimmter SoC über- oder unterschritten wird.'"
  "},"
  "{"
  //"'label':'Trigger bei SoC'," // Ohne Label wird die Gruppenüberschrift nicht angezeigt
  "'label_entry':'Rule',"
  "'groupsize':"+String(ANZAHL_RULES_TRIGGER_SOC)+","
  "'type':"+String(HTML_OPTIONGROUP)+","
  "'group':["
    "{"
        "'name':"+String(ID_PARAM_TRIGGER_AT_SOC)+","
        "'label':'Trigger',"
        "'type':"+String(HTML_INPUTSELECT)+","
        "'options':["
          "{'v':'0','l':'Aus'},"
          +comboAlarms+
          "],"
        "'default':'0',"
        "'dt':"+String(PARAM_DT_U8)+""
    "},"
    "{"
      "'name':"+String(ID_PARAM_TRIGGER_AT_SOC_ON)+","
      "'label':'SoC - Trigger ein',"
      "'unit':'%',"
      "'type':"+String(HTML_INPUTNUMBER)+","
      "'default':95,"
      "'min':1,"
      "'max':100,"
      "'dt':"+String(PARAM_DT_U8)+""
    "},"
    "{"
      "'name':"+String(ID_PARAM_TRIGGER_AT_SOC_OFF)+","
      "'label':'SoC - Trigger aus',"
      "'unit':'%',"
      "'type':"+String(HTML_INPUTNUMBER)+","
      "'default':80,"
      "'min':1,"
      "'max':100,"
      "'dt':"+String(PARAM_DT_U8)+""
    "}"
  "]}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";





// Inverter Charge
const String paramInverterCharge PROGMEM = "{'page':["

  // Ladestrom Zell-Spannungsabhängig drosseln'
  "{"
    "'label':'Ladestrom Zell-Spannungsabhängig drosseln',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_ZELLSPG_EN)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_ZELLSPG_STARTSPG)+","
    "'label':'Starten bei Zellspg. gr&ouml;ßer',"
    "'help':'Sobald die h&ouml;chste Zellspannung diesen Wert &uuml;bersteigt wird die Drosselung aktiv.',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3325',"
    "'min':2500,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_ZELLSPG_ENDSPG)+","
    "'label':'Maximale Zellspannung',"
    "'help':'Sobald die h&ouml;chste Zellspannung diesen Wert &uuml;bersteigt wird nur noch mit dem Mindest-Ladestrom geladen.\nHinweis: Der Wert muss gr&ouml;ßer sein als die Zell-Startspannung.\nAchtung: Bei aktivem Autobalancing wird diese Spannung durch die Balance-Zellspannung ersetzt!',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3300',"
    "'min':2500,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_ZELLSPG_MINDEST_STROM)+","
    "'label':'Mindest Ladestrom',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'5',"
    "'min':0,"
    "'max':200,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  // Ladestrom reduzieren bei Zelldrift
  "{"
    "'label':'Ladestrom reduzieren bei Zelldrift',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_ZELLDRIFT_EN)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_STARTSPG_ZELLE)+","
    "'label':'Starten bei Zellspg. gr&ouml;ßer',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3400',"
    "'min':2500,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_STARTABWEICHUNG)+","
    "'label':'Starten bei Drift gr&ouml;ßer',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'10',"
    "'min':1,"
    "'max':200,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_A_PRO_MV)+","
    "'label':'Reduzierung pro mV Abweichung',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'1',"
    "'min':1,"
    "'max':200,"
    "'dt':"+String(PARAM_DT_U8)+","
    "'help':'Die Reduzierung bezieht sich auf den eingestellten Maximalstrom'"
  "},"

  //Ladestrom reduzieren ab bestimmten SoC
  "{"
    "'label':'Ladestrom reduzieren - SoC',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_SOC_EN)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_AB_SOC)+","
    "'label':'Reduzierung ab SoC',"
    "'unit':'%',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'98',"
    "'min':1,"
    "'max':99,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_A_PRO_PERCENT_SOC)+","
    "'label':'Pro 1% um x A reduzieren',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTFLOAT_1)+","
    "'default':'10',"
    "'min':1,"
    "'max':1000,"
    "'dt':"+String(PARAM_DT_U16)+","
    "'help':'Die Reduzierung bezieht sich auf den eingestellten Maximalstrom'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_LADESTROM_REDUZIEREN_SOC_MINDEST_STROM)+","
    "'label':'Mindest Ladestrom',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'0',"
    "'min':0,"
    "'max':100,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  // Wenn eine Zelle z.B. >3.4V ist und das Delta zwischen größter und kleinster größer als z.B. 5mV ist,
  // dann Ladespannung reduzieren.
  "{"
    "'label':'Dynamische Ladespannungsbegrenzung (Beta!)',"
    "'type':"+String(HTML_SEPARATION)+","
    "'help':'Sobald die Spannung einer Zelle und das Delta zwischen der niedrigsten und der höchsten Zellenspannung größer als eingestellt werden,\nwird die Ladespannung dynamisch angepasst, um die maximale Ladeleistung zu erreichen, ohne dass die Zellen weiter auseinander driften.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_VOLTAGE_DYNAMIC_REDUCE_EN)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_VOLTAGE_DYNAMIC_REDUCE_ZELLSPG)+","
    "'label':'Start-Zellspannung',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3400',"
    "'min':2000,"
    "'max':4000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_VOLTAGE_DYNAMIC_REDUCE_DELTA)+","
    "'label':'Spg.-Delta Min/Max',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'5',"
    "'min':1,"
    "'max':100,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  // Autobalance'
  "{"
    "'label':'Autobalance',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_ENABLE)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_START_INTERVAL)+","
    "'label':'Balance-Intervall',"
    "'help':'Gibt die Tage an, nach denen wieder das Balancing gestartet werden soll.\nHinweis: Wenn der Autobalancer aktiv, dann ist in der Ballance-Zeit der Charge-Current Cut-Off deaktiviert!\nEs muss die richtige Anzahl der Zellen in den Serial-Settings eingestellt sein!',"
    "'unit':'T',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'5',"
    "'min':1,"
    "'max':30,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_START_CELLVOLTAGE)+","
    "'label':'Start Zellspannung',"
    "'help':'Zellspannung die erreicht sein muss, damit der Vorgang beginnt.',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3300',"
    "'min':2500,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_MINDEST_TIME)+","
    "'label':'Balance Mindest-Zeit',"
    "'help':'So lange läuft das Balancing mindestens',"
    "'unit':'Min',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'0',"
    "'min':0,"
    "'max':600,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_CHARGE_VOLTAGE)+","
    "'label':'Balance-Ladespannung',"
    "'help':'Die Max. Ladespannung wird während dem Autobalancing auf diese Spannung angehoben.',"
    "'unit':'V',"
    "'type':"+String(HTML_INPUTFLOAT_1)+","
    "'default':'552',"
    "'min':50,"
    "'max':60,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_CHARGE_CELLVOLTAGE)+","
    "'label':'Balance-Zellspannung',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3450',"
    "'min':2500,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_CELLDIF_FINISH)+","
    "'label':'Celldif. fertig',"
    "'help':'Balancing ist fertig, wenn die eingestellte Zelldifferenz erreicht ist.',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'5',"
    "'min':0,"
    "'max':50,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_AUTOBALANCE_TIMEOUT)+","
    "'label':'Timeout',"
    "'help':'Ist in dieser Zeit das Balancing nicht fertig, wird der Vorgang abgebrochen.',"
    "'unit':'Min',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'60',"
    "'min':0,"
    "'max':600,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"

  //Charge-Current Cut-Off
  "{"
    "'label':'Charge-Current Cut-Off',"
    "'type':"+String(HTML_SEPARATION)+","
    "'help':'Liegt der Ladestrom die eingestellte Zeit (Cut-Off Time) unter dem Cut-Off Strom, wird der Ladestrom so lange auf 0 A gesetzt, bis der \"Float Ladespannung SoC\" unterschritten wird.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_CURRENT_CUT_OFF_ENABLE)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_CURRENT_CUT_OFF_TIME)+","
    "'label':'Cut-Off Time',"
    "'unit':'s',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'300',"
    "'min':1,"
    "'max':30000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_CURRENT_CUT_OFF_CURRENT)+","
    "'label':'Cut-Off Strom',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTFLOAT_1)+","
    "'default':'10',"
    "'min':0,"
    "'max':10000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_CHARGE_CURRENT_CUT_OFF_START_VOLTAGE)+","
    "'label':'Start Zellspannung',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'0',"
    "'min':0,"
    "'max':3500,"
    "'dt':"+String(PARAM_DT_U16)+","
    "'help':'Die Regelung wird erst aktiv, wenn die Zellspannung erreicht ist.\n0 = Startvoltage deaktiviert'"
  "},"

  //Bei unterschreiten von Zellspannung melde SoC x%
  "{"
    "'label':'SoC beim Unterschreiten der Zellspannung',"
    "'type':"+String(HTML_SEPARATION)+","
    "'help':'Wenn die eingestellte Zellspannung für den Ladebeginn unterschritten wird, dann kann durch das Senden eines beliebigen SoC an den Wechselrichter ein Nachladen veranlasst werden.\nEs wird so lange nachgeladen, bis die Zellspannung Ladeende überschritten wird.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_SOC_BELOW_ZELLSPANNUNG_EN)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_SOC_BELOW_ZELLSPANNUNG_SPG)+","
    "'label':'Zellspannung Ladebeginn',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3000',"
    "'min':2500,"
    "'max':4000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_SOC_BELOW_ZELLSPANNUNG_SPG_END)+","
    "'label':'Zellspannung Ladeende',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'0',"
    "'min':0,"
    "'max':4000,"
    "'dt':"+String(PARAM_DT_U16)+","
    "'help':'Wenn Zellspannung Ladeende 0, dann wird geladen, bis die Zellspannung Ladebeginn wieder überschritten wird.'"
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_SOC_BELOW_ZELLSPANNUNG_SOC)+","
    "'label':'SoC',"
    "'unit':'%',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'9',"
    "'min':1,"
    "'max':100,"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_SOC_BELOW_ZELLSPANNUNG_TIME)+","
    "'label':'Sperrzeit zwischen zwei Nachladungen',"
    "'unit':'s',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'600',"
    "'min':0,"
    "'max':3600,"
    "'dt':"+String(PARAM_DT_U16)+""
  "}"

  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


  // Inverter Discharge
  const String paramInverterDischarge PROGMEM = "{'page':["

  // Entladestrom Zell-Spannungsabhängig drosseln'
  "{"
    "'label':'Entladestrom Zell-Spannungsabhängig drosseln',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_ENTLADESTROM_REDUZIEREN_ZELLSPG_EN)+","
    "'label':'Ein/Aus',"
    "'type':"+String(HTML_INPUTCHECKBOX)+","
    "'default':'0',"
    "'dt':"+String(PARAM_DT_BO)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_ENTLADESTROM_REDUZIEREN_ZELLSPG_STARTSPG)+","
    "'label':'Starten bei Zellspg. kleiner',"
    "'help':'Sobald die niedrigste Zellspannung diesen Wert unterschreitet wird die Drosselung aktiv.',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'0',"
    "'min':0,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_ENTLADESTROM_REDUZIEREN_ZELLSPG_ENDSPG)+","
    "'label':'End Zellspannung',"
    "'help':'Sobald die niedrigste Zellspannung diesen Wert unterschreitet wird maxmial noch mit dem Mindest-Entladestrom entladen.\nHinweis: Der Wert muss kleiner sein als die Zell-Startspannung.',"
    "'unit':'mV',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'3300',"
    "'min':2500,"
    "'max':5000,"
    "'dt':"+String(PARAM_DT_U16)+""
  "},"
  "{"
    "'name':"+String(ID_PARAM_INVERTER_ENTLADESTROM_REDUZIEREN_ZELLSPG_MINDEST_STROM)+","
    "'label':'Mindest Entladestrom',"
    "'unit':'A',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':'1',"
    "'min':0,"
    "'max':200,"
    "'dt':"+String(PARAM_DT_U8)+""
  "}"

  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";


const String paramDataDeviceMapping PROGMEM = "{'page':["
  // Datadevice mapping 
  "{"
    "'label':'Data device mapping',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'label':'Data device mapping',"
    "'label_entry':'Data device',"
    "'groupsize':"+String(MUBER_OF_DATA_DEVICES)+","
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'group':["
      "{"
      "'name':"+String(ID_PARAM_DEVICE_MAPPING_SCHNITTSTELLE)+","
      "'label':'Schnittstelle',"
      "'type':"+String(HTML_INPUTSELECT)+","
      "'options':["
        "{'v':'255','l':'Nicht belegt'},"
        +bmsDeviceAll+
        "],"
      "'default':255,"
      "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_DEVICE_MAPPING_ADRESSE)+","
        "'label':'Adresse',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':0,"
        "'min':0,"
        "'max':18,"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_DEVICE_MAPPING_NAME)+","
        "'label':'Name',"
        "'type':"+String(HTML_INPUTTEXT)+","
        "'default':'',"
        "'max':10,"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_ST)+""
      "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";





const String paramDeviceNeeyBalancer PROGMEM = "{'page':["
  "{"
    "'label':'NEEY Active Balancer',"
    "'label_entry':'NEEY',"
    "'groupsize':3,"
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'depId':"+String(ID_PARAM_SS_BTDEV)+","    //dependence
    "'depVal':["
      "{'v':'"+String(ID_BT_DEVICE_NEEY4A)+"'},"
      "{'v':'"+String(ID_BT_DEVICE_NEEY8A)+"'}],"
    "'depDt':1,"  //dependence   DT_ID_PARAM_SS_BTDEV
    "'group':["
      "{"
        "'name':"+String(ID_PARAM_NEEY_BALANCER_ON)+","
        "'label':'Balancer On',"
        "'type':"+String(HTML_INPUTSELECT)+","
        "'options':["
          "{'v':'0','l':'Aus'},"
          "{'v':'110','l':'Ein'},"
          +comboAlarms+
          "],"
        "'default':'0',"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_CELLS)+","
        "'label':'Cells',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':16,"
        "'min':4,"
        "'max':24,"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_U8)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_START_VOLTAGE)+","
        "'label':'Differenz Voltage',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':0.005,"
        "'min':0,"
        "'max':1,"
        "'unit':'V',"
        "'step':0.001,"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_MAX_BALANCE_CURRENT)+","
        "'label':'Max. Balance Current',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':4.0,"
        "'min':0.1,"
        "'max':8,"
        "'unit':'A',"
        "'step':'0.01',"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_SLEEP_VOLTAGE)+","
        "'label':'Sleep Voltage',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':3.30,"
        "'min':1,"
        "'max':5,"
        "'unit':'V',"
        "'step':'0.001',"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_EQUALIZATION_VOLTAGE)+","
        "'label':'Equalization Voltage',"
        "'type':"+String(HTML_INPUTFLOAT)+","
        "'default':3.31,"
        "'min':1,"
        "'max':5,"
        "'unit':'V',"
        "'step':'0.001',"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_FL)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_BAT_CAPACITY)+","
        "'label':'Bat. Capacity',"
        "'type':"+String(HTML_INPUTNUMBER)+","
        "'default':200,"
        "'min':1,"
        "'max':500,"
        "'unit':'Ah',"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_U16)+""
      "},"
      "{"
        "'name':"+String(ID_PARAM_NEEY_BAT_TYPE)+","
        "'label':'BatType',"
        "'type':"+String(HTML_INPUTSELECT)+","
        "'options':["
          "{'v':'1','l':'NCM'},"
          "{'v':'2','l':'LFP'},"
          "{'v':'3','l':'LTO'},"
          "{'v':'4','l':'PbAc'}],"
        "'default':'2',"
        "'flash':'1',"
        "'dt':"+String(PARAM_DT_U8)+""
      "}"

      //Buzzer mode (Shut)
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'},{'label':'Read from NEEY','name':'read-btn'},{'label':'Write to NEEY','name':'write-btn'}],"
  "'timer':[{'type':'text','interval':2000}]"
  "}";


const String paramDeviceJbdBms PROGMEM = "{'page':["
  "{"
    "'label':'JBD BMS',"
    "'label_entry':'Serial',"
    "'groupsize':11,"
    "'type':"+String(HTML_OPTIONGROUP)+","
    "'depId':"+String(ID_PARAM_SERIAL_CONNECT_DEVICE)+","    //dependence
    "'depVal':"+String(ID_SERIAL_DEVICE_JBDBMS)+","          //dependence
    "'depDt':1,"                                             //dependence; depVal=Datatype der depId
    "'group':["
    "{"
      "'name':"+String(ID_PARAM_JBD_CELL_VOLTAGE_100)+","
      "'label':'Cellvoltage 100%',"
      "'type':"+String(HTML_INPUTNUMBER)+","
      "'default':3400,"
      "'min':1000,"
      "'max':5000,"
      "'unit':'mV',"
      "'flash':'1',"
      "'dt':"+String(PARAM_DT_U16)+""
    "}"
    "]"
  "}"
  "],"
  "'btn':[{'name':'save-btn','label':'Save'}]"
  "}";




const String paramDeviceBpn PROGMEM = "{'page':["
  // General
  "{"
    "'label':'General',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_NR_OF_CELLS)+","
    "'label':'Anzahl Zellen',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':16,"
    "'min':0,"
    "'max':18,"
    "'unit':''"
  "},"

  // Shunt
  "{"
    "'label':'Shunt',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_NOMINAL_BAT_CAPACITY)+","
    "'label':'Nominal Capacity',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':280,"
    "'min':0,"
    "'max':1000,"
    "'unit':'Ah'"
  "},"

  //Ausgänge
  "{"
    "'label':'Ausgänge',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_RELAIS1_MODE)+","
    "'label':'Relais 1',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Arbeitsstrom'},"
      "{'v':'1','l':'Ruhestrom'}"
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_RELAIS2_MODE)+","
    "'label':'Relais 2',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Arbeitsstrom'},"
      "{'v':'1','l':'Ruhestrom'}"
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  // Alarm
  "{"
    "'label':'Alarm - Cell coltage',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_LOW_CELL_VOLTAGE)+","
    "'label':'Low Cell Voltage',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':2700,"
    "'min':2500,"
    "'max':4000,"
    "'unit':'mV'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_HIGH_CELL_VOLTAGE)+","
    "'label':'High Cell Voltage',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':3600,"
    "'min':2500,"
    "'max':4000,"
    "'unit':'mV'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_DELAY_CELL_VOLTAGE)+","
    "'label':'Alarm Delay - Cell Voltage',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':16,"
    "'min':0,"
    "'max':255,"
    "'unit':'s'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_RELAIS_CELL_VOLTAGE)+","
    "'label':'Ausgang',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Aus'},"
      "{'v':'1','l':'Relais 1'},"
      "{'v':'2','l':'Relais 2'},"
      "{'v':'2','l':'DO'}"
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'Alarm - Battery voltage',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_LOW_BATTERY_VOLTAGE)+","
    "'label':'Low Battery Voltage',"
    "'type':"+String(HTML_INPUTFLOAT)+","
    "'step':'0.01',"
    "'default':57.6,"
    "'min':0,"
    "'max':70,"
    "'unit':'V'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_HIGH_BATTERY_VOLTAGE)+","
    "'label':'High Battery Voltage',"
    "'type':"+String(HTML_INPUTFLOAT)+","
    "'step':'0.01',"
    "'default':57.6,"
    "'min':0,"
    "'max':70,"
    "'unit':'V'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_DELAY_BATTERY_VOLTAGE)+","
    "'label':'Alarm Delay - Battery Voltage',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':0,"
    "'min':0,"
    "'max':255,"
    "'unit':'s'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_RELAIS_BATTERY_VOLTAGE)+","
    "'label':'Ausgang',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Aus'},"
      "{'v':'1','l':'Relais 1'},"
      "{'v':'2','l':'Relais 2'},"
      "{'v':'2','l':'DO'}"
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'Alarm - Charge current',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_MAX_CHARGE_CURRENT)+","
    "'label':'Max Charge Current',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':100,"
    "'min':0,"
    "'max':4000,"
    "'unit':'A'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_DELAY_MAX_CHARGE_CURRENT)+","
    "'label':'Alarm Delay - Charge Current',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':0,"
    "'min':0,"
    "'max':255,"
    "'unit':'s'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_RELAIS_CHARGE_CURRENT)+","
    "'label':'Ausgang',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Aus'},"
      "{'v':'1','l':'Relais 1'},"
      "{'v':'2','l':'Relais 2'},"
      "{'v':'2','l':'DO'}"
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "},"

  "{"
    "'label':'Alarm - Discharge current',"
    "'type':"+String(HTML_SEPARATION)+""
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_MAX_DISCHARGE_CURRENT)+","
    "'label':'Max Discharge Current',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':100,"
    "'min':0,"
    "'max':4000,"
    "'unit':'A'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_DELAY_MAX_DISCHARGE_CURRENT)+","
    "'label':'Alarm Delay - Discharge Current',"
    "'type':"+String(HTML_INPUTNUMBER)+","
    "'default':0,"
    "'min':0,"
    "'max':255,"
    "'unit':'s'"
  "},"
  "{"
    "'name':"+String(BPN_SETTINGS_ALARM_RELAIS_DISCHARGE_CURRENT)+","
    "'label':'Ausgang',"
    "'type':"+String(HTML_INPUTSELECT)+","
    "'options':["
      "{'v':'0','l':'Aus'},"
      "{'v':'1','l':'Relais 1'},"
      "{'v':'2','l':'Relais 2'},"
      "{'v':'2','l':'DO'}"
      "],"
    "'default':'0',"
    "'dt':"+String(PARAM_DT_U8)+""
  "}"

  "],"
  "'sys':{'store':0},"
  "'btn':[{'name':'save-btn','label':'Write to BPN'},{'name':'read-btn','label':'Read from BPN'}],"
  "'timer':[{'type':'json','interval':2000}]"
  "}";

